version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9443:9443
    restart: always

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscaled
    network_mode: host
    environment:
      - TS_AUTH_ONCE=true
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_ROUTES=${TS_ROUTES}
      - TS_EXTRA_ARGS=--advertise-exit-node
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/lib:/var/lib
      - /var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    restart: always

#  pihole:
#    image: pihole/pihole:latest
#    container_name: pihole
#    hostname: pi.hole
#    environment:
#      - WEBPASSWORD=
#    ports:
#      - 53:53/tcp
#      - 53:53/udp
#      - 80:80/tcp
#    restart: unless-stopped

  graphite-statsd:
    container_name: graphite
    restart: always
    ports:
        - '80:80'
        - '2003-2004:2003-2004'
        - '2023-2024:2023-2024'
        - '8125:8125/udp'
        - '8126:8126'
    image: graphiteapp/graphite-statsd

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - '3000:3000'
    restart: always

