services:

  #agent:
  #  image: portainer/agent:latest
  #  container_name: portainer_agent
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - /var/lib/docker/volumes:/var/lib/docker/volumes
  #  ports:
  #    - 9001:9001
  #  restart: always

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin-config:/config
      - $JELLYFIN_DATA_PATH/cache:/cache
      - $JELLYFIN_DATA_PATH/media:/media
    restart: always

  #filebrowser:
  #  image: filebrowser/filebrowser
  #  container_name: filebrowser
  #  user: "${UID}:${GID}"
  #  ports:
  #    - 8080:80
  #  volumes:
  #    - $FILEBROWSER_DATA_PATH/srv:/srv
  #    - $FILEBROWSER_DATA_PATH/branding:/branding
  #    - $FILEBROWSER_DATA_PATH/database.db:/database.db
  #    - $FILEBROWSER_DATA_PATH/.filebrowser.json:/.filebrowser.json
  #  restart: always

  copyparty:
    container_name: copyparty
    image: copyparty/ac
    ports:
      - 8086:8086
      - 3923:3923
    volumes:
      - $COPYPARTY_DATA_PATH:/w
      - ./copyparty-cfg:/cfg
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: always
