version: '3'

services:
  agent:
    image: 'portainer/agent:latest'
    container_name: portainer_agent
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    ports:
      - '9001:9001'
    restart: always
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /mnt/media/jellyfin-config:/config
      - /mnt/media/jellyfin-cache:/cache
      - /media/jellyfin-media/music:/media/Music
      - /media/jellyfin-media/movies:/media/Movies
    restart: 'unless-stopped'
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /media/calibre-media/config:/config
      - /media/calibre-media/library:/books
    ports:
      - 8083:8083
    restart: unless-stopped
  nextcloud-aio:
    container_name: nextcloud-aio-mastercontainer
    ports:
        - 80:80
        - 8080:8080
        - 8443:8443
    volumes:
        - /media/nextcloud-datastore/nextcloud_aio_mastercontainer:/mnt/docker-aio-config
        - /var/run/docker.sock:/var/run/docker.sock:ro
    image: nextcloud/all-in-one:latest
    restart: always
