version: '3'

services:
  agent:
    image: 'portainer/agent:latest'
    container_name: portainer_agent
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    ports:
      - '9001:9001'
    restart: always
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - $JELLYFIN_MEDIA_PATH/config:/config
      - $JELLYFIN_MEDIA_PATH/cache:/cache
      - $JELLYFIN_MEDIA_PATH/media:/media
    restart: 'unless-stopped'
  filebrowser:
    image: filebrowser/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 8080:80
    volumes:
      - $FILESHARE_DATA_PATH/srv:/srv
      - $FILESHARE_DATA_PATH/branding:/branding
      - $FILESHARE_DATA_PATH/database.db:/database.db
      - $FILESHARE_DATA_PATH/.filebrowser.json:/.filebrowser.json
    restart: always
