version: '3'

services:
  agent:
    image: 'portainer/agent:latest'
    container_name: portainer_agent
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
    ports:
      - '9001:9001'
    restart: always
  #nginx:
  #	image: nginx
	#	volumes:
	#		- /var/run/docker.sock:/var/run/docker.sock
	#	ports:
	#		- 80:80
	#	logging:
	#		options:
	#			max-size: 1g
	#	restart: always
  mc:
    image: "itzg/minecraft-server"
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: true
      SERVER_NAME: "Minecraft Server"
      MOTD: "tip: don't drink the tap water"
      TYPE: "PAPER"
      VERSION: "1.20.4"
      LEVEL: "world"
      DIFFICULTY: "hard"
      PLUGINS: "https://github.com/playit-cloud/playit-minecraft-plugin/releases/latest/download/playit-minecraft-plugin.jar"
      VIEW_DISTANCE: 24
      MEMORY: "8G"
      ENABLE_ROLLING_LOGS: true
      ENABLE_AUTOPAUSE: true
      MAX_TICK_TIME: "-1"
      JVM_DD_OPTS: "disable.watchdog:true"
      SNOOPER_ENABLED: false
      UID: 1000
      GID: 1000
    volumes:
      - "/media/hosting-datastore/minecraft/data:/data"
