version: '3'

services:
  #portainer agent
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "VANILLA"
      VERSION: "LATEST"
      ICON: "icon.png"
      OVERRIDE_ICON: true
      SERVER_NAME: "Heavy Metal Poisoning Simulator 2023"
      MOTD: "lead water enjoyers only"
      MAX_TICK_TIME: -1
      SNOOPER_ENABLED: false
      ENABLE_AUTOPAUSE:  true
      ENABLE_ROLLING_LOGS: true
    tty: true
    stdin_open: true
    volumes:
      - /media/usb-hdd/docker-data-store/minecraft-server:/data
    ports:
      - 25565:25565
    restart: unless-stopped
