version: '3'

services:
  #portainer agent
  nginx:
  	image: nginx
  	
		volumes:
			- /var/run/docker.sock:/var/run/docker.sock
		ports:
			- 80:80
		logging:
			options:
				max-size: 1g
		restart: always
		
